spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/${AUTH_DATABASE}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
auth:
  registered-client-id: ${AUTH_REGISTERED_CLIENT_ID}
  client-id: ${AUTH_CLIENT_ID}
  client-secret: ${AUTH_CLIENT_SECRET}
  authorized-redirect: ${AUTH_AUTHORIZED_REDIRECT}
  login-redirect: ${AUTH_LOGIN_REDIRECT}
